server:
  port: 9999
#  thymeleaf
spring:
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    cache: false
#
  mvc:
    static-path-pattern:/**
#  mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(31j5UIsWLrUGfEcje+l1dHl367shbysDtYgyOcxmvsnfJCuqOuIFVDf2yQ0ERTjI)
    username: ENC(hyOS4qF0VQca/jorP6kneA==)
    password: ENC(sdsvEGnIega+SsiMLttZeb1JZF+sRb8d)
# redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 101.132.79.66
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码
    password: ENC(sdsvEGnIega+SsiMLttZeb1JZF+sRb8d)
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 5120
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 1000
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 3000
  # spring-session 使用,none:不使用
  session:
    store-type: none
# mybatis
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.value.entities
# jasypt加密的密匙
jasypt:
  encryptor:
    password: 


